/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models/chair.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chair.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.033, 0.54, -0.236]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.483, 0.45, -0.405]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.001, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.094, 0.1, 0.1]}>
            <group position={[0.013, 0, 0]}>
              <mesh geometry={nodes['Cylinder001_Material_#2146932551_0'].geometry} material={materials.Material_2146932551} position={[-482.023, -815.541, 14.481]} scale={1.018} />
            </group>
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.007, 0.135, 0.155]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.365, 0, 0.365]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0.003, 0.544, 0.173]} scale={[0.4, 0.076, 0.4]} />
    </group>
  )
}

useGLTF.preload('/chair.gltf')
